name: Build with Nuitka (musl-compatible, Alpine)

on:
  workflow_dispatch:
    inputs:
        ref:
            type: string
            description: 'Git ref from which to release'
            required: true
            default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build on python:3.10-alpine for musl
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Docker (Alpine)
        run: |
          docker run --rm \
            -v "$PWD":/src -w /src \
            python:3.10-alpine sh -c "
              apk add --no-cache binutils curl patchelf gcc g++ musl-dev &&
              wget -O python-musl.tar.gz https://github.com/astral-sh/python-build-standalone/releases/download/20250630/cpython-3.10.18+20250630-x86_64-unknown-linux-musl-install_only.tar.gz &&
              mkdir -p python-musl &&
              tar -xzf python-musl.tar.gz -C python-musl --strip-components=1 &&
              ./python-musl/bin/python3 -m ensurepip &&
              ./python-musl/bin/pip3 install -U pip setuptools wheel &&
              ./python-musl/bin/pip3 install -r requirements.txt &&
              ./python-musl/bin/pip3 install nuitka &&
              ./python-musl/bin/nuitka --standalone --output-dir=dist ad.py &&
              ./python-musl/bin/nuitka --standalone --output-dir=dist down_aria2.py &&
              chmod +x dist/ad.dist/ad.bin dist/down_aria2.dist/down_aria2.bin
            "

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ad-musl
          path: dist/ad.dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: down_aria2-musl
          path: dist/down_aria2.dist/
