name: Build Python binary test2

on:
  workflow_dispatch:

jobs:
  build:
    name: Build aarch64 musl binary
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git wget curl \
              python3 python3-pip scons \
              patchelf upx squashfs-tools \
              g++ gcc unzip zlib1g-dev

      - name: Clone and build musl-cross-make
        run: |
          git clone https://github.com/richfelker/musl-cross-make.git
          cd musl-cross-make
          echo 'TARGET = aarch64-linux-musl' > config.mak
          echo 'OUTPUT = /opt/musl-cross' >> config.mak
          make -j$(nproc)
          sudo make install

      - name: Install Nuitka
        run: |
          pip install -U nuitka

      - name: Compile ad.py with musl-gcc and Nuitka
        run: |
          mkdir -p build

          export CC=/opt/musl-cross/bin/aarch64-linux-musl-gcc
          export CXX=/opt/musl-cross/bin/aarch64-linux-musl-g++
          export AR=/opt/musl-cross/bin/aarch64-linux-musl-ar
          export RANLIB=/opt/musl-cross/bin/aarch64-linux-musl-ranlib

          nuitka ad.py \
            --onefile \
            --standalone \
            --remove-output \
            --nofollow-import-to=*.tests \
            --static-libpython=yes \
            --output-dir=build

          mv build/ad.bin build/ad

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm64-musl
          path: build/
