name: Build Executables

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: 'Git ref from which to release'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    container: alpine:latest
    strategy:
      matrix:
        script: [down_aria2, test]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        ref: '${{ github.event.inputs.ref }}'

    - name: update lib
      run: |
          apt update
          apt install -y build-essential musl-tools gcc-multilib g++-multilib zlib1g-dev python3-dev python3-pip
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller    
        pip install -r requirements.txt
   
    - name: Build executables
      run: |
        pyinstaller --onefile  --static ${{ matrix.script }}.py 

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.script }}
        path: dist/${{ matrix.script }}
