
name: Build Nuitka Binary for OpenWrt aarch64-musl

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build arm64 (musl/Alpine)
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Docker (Alpine)
        run: |
          docker run --rm \
            -v "$PWD":/src -w /src \
            python:3.10-alpine sh -c "
              apk add --no-cache binutils curl patchelf gcc musl-dev  &&
              pip install -r requirements.txt &&
              pip install nuitka &&
              CC=musl-gcc nuitka --standalone --onefile --static-libpython=yes --output-dir=dist --nofollow-import-to=numpy --remove-output down_aria2.py
            "

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm64-alpine
          path: dist/
