name: Build Executables

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.runs_on }}
    container: 
      image: python:3.10-alpine
    
    strategy:
      matrix:
        include:
          - runs_on: ubuntu-22.04   # x86 架构
            platform: x64
          - runs_on: ubuntu-22.04-arm  # ARM 架构
            platform: arm64
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: update lib
      run: |
          apk update
          apk add binutils curl
        
    - name: Install Dependencies
      run: |
        pip install pyinstaller    
        pip install -r requirements.txt
    
    - name: Build executables
      run: |
        pyinstaller --onefile --distpath=down_aria2 down_aria2.py
        pyinstaller --onefile --distpath=ad ad.py
        pyinstaller --onefile --distpath=ad2 ad2.py 


    - name: zip
      run: |
        mkdir file
        cp down_aria2/down_aria2 file
        cp ad/ad file
        cp ad2/ad2 file
        tar -czvf ${{ matrix.platform }}-file.tar.gz file


    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: ${{ matrix.platform }}-file.tar.gz application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
