name: Build Executables

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: 'Git ref from which to release'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    container: python:3.10-alpine
    strategy:
      matrix:
        script: [down_aria2, test]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        ref: '${{ github.event.inputs.ref }}'

    - name: update lib
      run: |
          apk update
          apk add binutils curl
        
    - name: Install Dependencies
      run: |
        # python -m pip install --upgrade pip
        pip install pyinstaller    
        pip install -r requirements.txt
   
    - name: Build executables
      run: |
        pyinstaller --onefile ${{ matrix.script }}.py 

        curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @dist/${{ matrix.script }} \
            "https://uploads.github.com/repos/${{ github.repository }}/actions/artifacts?name=${{ matrix.script }}" 
        
    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: ${{ matrix.script }}
    #     path: dist/${{ matrix.script }}
