name: Build with Termux Docker
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Termux in Docker
        run: |

          docker pull termux/package-builder:latest
          
          docker run --rm -v $PWD:/work termux/package-builder:latest bash -c "
            cd /work
            # 更新系统并安装依赖（使用apt而非pkg）
            apt update && apt upgrade -y
            apt install -y python3 python3-pip python3-venv python3-dev gcc g++ make
            
            # 创建虚拟环境以绕过系统Python限制
            python3 -m venv venv
            source venv/bin/activate
            
            # 安装Nuitka（允许系统级安装）
            pip install nuitka --break-system-packages
            
            # 打包Python脚本
            python -m nuitka --standalone --onefile \
              --output-dir=dist \
              --nofollow-import-to=numpy \
              --remove-output \
              --static-libpython=no \
              down_aria2.py
            
            # 复制输出文件到挂载目录
            cp dist/down_aria2 /work/
          "

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: termux-docker-output
          path: down_aria2
