name: Build with Termux Docker
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Termux in Docker
        run: |

          docker pull termux/package-builder:latest
          
          docker run --rm -v $PWD:/work termux/package-builder:latest bash -c "
            cd /work
            pkg update && pkg upgrade -y
            pkg install python python-pip -y
            pip install nuitka
            python -m nuitka --standalone --onefile down_aria2.py
          "

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: termux-docker-output
          path: down_aria2
