name: Build with Nuitka
on:
  workflow_dispatch:
    inputs:
        ref:
            type: string
            description: 'Git ref from which to release'
            required: true
            default: 'main'

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        include:
          - runs_on: ubuntu-22.04
            platform: x64
          - runs_on: ubuntu-22.04-arm
            platform: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install nuitka
        run: |
          pip install -r requirements.txt
          pip install nuitka

      - name: Build executable
        run: |
          nuitka --standalone --onefile --static-libpython=yes --output-dir=dist --nofollow-import-to=numpy --remove-output ad.py
          nuitka --standalone --onefile --static-libpython=yes --output-dir=dist --nofollow-import-to=numpy --remove-output down_aria2.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: dist/
