name: Build Python Executables

on:
  workflow_dispatch:
    inputs:
        ref:
            type: string
            description: 'Git ref from which to release'
            required: true
            default: 'main'

jobs:
  build-x86_64:
    name: Build x86_64 (glibc)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pyinstaller
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build x86_64 executable
        run: |
          pyinstaller --name ad --onedir --distpath=dist ad.py
          pyinstaller --name down_aria2 --onedir --distpath=dist down_aria2.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64
          path: dist/


  build-x64-alpine:
    name: Build x86_64 (musl/Alpine)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Docker (Alpine)
        run: |
          docker run --rm \
            -v "$PWD":/src -w /src \
            python:3.10-alpine sh -c "
              apk add --no-cache binutils curl &&
              pip install -r requirements.txt &&
              pip install pyinstaller &&
              pyinstaller --name ad --onedir --distpath=dist ad.py &&
              pyinstaller --name down_aria2 --onedir --distpath=dist down_aria2.py
            "
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x64_alpine
          path: dist/

  build-alpine:
    name: Build arm64 (musl/Alpine)
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Docker (Alpine)
        run: |
          docker run --rm \
            -v "$PWD":/src -w /src \
            python:3.10-alpine sh -c "
              apk add --no-cache binutils curl &&
              pip install -r requirements.txt &&
              pip install pyinstaller &&
              pyinstaller --name ad --onedir --distpath=dist ad.py &&
              pyinstaller --name down_aria2 --onedir --distpath=dist down_aria2.py
            "

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm64-alpine
          path: dist/
